#!/bin/bash
# modules/report/main.sh - 报表模块（Oracle数据报表）

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "错误: 此脚本应该被 source 调用" >&2
    exit 1
fi

log_info "报表模块加载中..."

REPORT_DIR="${REPORT_DIR:-$PROJECT_ROOT/reports}"

cleanup_report() {
    log_info "清理报表模块"
    safe_rm_dir "$TEMP_BASE_DIR/report"
}

# 生成HTML报表
report_generate() {
    local report_type="$1"
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local report_file="$REPORT_DIR/${report_type}_${timestamp}.html"
    local data_file="$TEMP_BASE_DIR/report/data_${timestamp}.txt"
    
    log_info "生成报表: $report_type"
    mkdir -p "$REPORT_DIR" "$TEMP_BASE_DIR/report"
    
    # 获取Oracle数据
    if [[ "$report_type" == "oracle_pipeline_report" ]]; then
        # 收集Oracle统计信息
        sqlplus -S "$(_oracle_connect_string)" <<EOF > "$data_file"
SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

PROMPT <h2>数据库基本信息</h2>
PROMPT <table border='1'>
PROMPT <tr><th>属性</th><th>值</th></tr>
SELECT '<tr><td>数据库名称</td><td>' || name || '</td></tr>' FROM v\$database;
SELECT '<tr><td>打开模式</td><td>' || open_mode || '</td></tr>' FROM v\$database;
SELECT '<tr><td>日志模式</td><td>' || log_mode || '</td></tr>' FROM v\$database;
SELECT '<tr><td>当前时间</td><td>' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || '</td></tr>' FROM DUAL;
PROMPT </table>

PROMPT <h2>表空间使用情况</h2>
PROMPT <table border='1'>
PROMPT <tr><th>表空间名</th><th>已用(GB)</th><th>总大小(GB)</th><th>使用率(%)</th></tr>
SELECT '<tr><td>' || tablespace_name || '</td><td>' || 
       ROUND(used_space * 8 / 1024, 2) || '</td><td>' ||
       ROUND(tablespace_size * 8 / 1024, 2) || '</td><td>' ||
       ROUND((used_space / tablespace_size) * 100, 2) || '</td></tr>'
FROM dba_tablespace_usage_metrics;
PROMPT </table>

PROMPT <h2>活跃会话</h2>
PROMPT <table border='1'>
PROMPT <tr><th>用户名</th><th>会话数</th></tr>
SELECT '<tr><td>' || username || '</td><td>' || COUNT(*) || '</td></tr>'
FROM v\$session 
WHERE username IS NOT NULL AND status='ACTIVE'
GROUP BY username
ORDER BY COUNT(*) DESC;
PROMPT </table>

EXIT;
EOF
    fi
    
    # 生成HTML报表
    cat > "$report_file" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Oracle报表 - $report_type</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; border-bottom: 2px solid #333; }
        h2 { color: #666; margin-top: 20px; }
        table { border-collapse: collapse; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #4CAF50; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .summary { background-color: #e7f3ff; padding: 10px; border-left: 4px solid #2196F3; margin: 20px 0; }
        .footer { font-size: 12px; color: #999; text-align: center; margin-top: 30px; }
    </style>
</head>
<body>
    <h1>Oracle数据库报表</h1>
    <div class="summary">
        <strong>报表类型:</strong> $report_type<br>
        <strong>生成时间:</strong> $(date '+%Y-%m-%d %H:%M:%S')<br>
        <strong>模块名称:</strong> $MODULE_NAME<br>
        <strong>主机名:</strong> $(hostname)
    </div>
    
    $(cat "$data_file" 2>/dev/null || echo "<p>无数据</p>")
    
    <hr>
    <div class="footer">
        Generated by Oracle Backup System v2.0<br>
        报表文件: $report_file
    </div>
</body>
</html>
EOF
    
    if [[ -f "$report_file" ]]; then
        log_success "报表生成: $report_file"
        echo "$report_file"
        return 0
    else
        log_error "报表生成失败"
        return 1
    fi
}

# 生成PDF报表（需要额外工具）
report_generate_pdf() {
    local html_file="$1"
    local pdf_file="${html_file%.html}.pdf"
    
    log_info "生成PDF报表: $pdf_file"
    
    if command -v wkhtmltopdf &>/dev/null; then
        wkhtmltopdf "$html_file" "$pdf_file"
        log_success "PDF报表生成: $pdf_file"
        echo "$pdf_file"
    else
        log_warn "wkhtmltopdf不可用，跳过PDF生成"
        echo "$html_file"
    fi
}

# 模块主函数
report_main() {
    log_info "报表模块就绪"
    mkdir -p "$REPORT_DIR"
    log_info "报表目录: $REPORT_DIR"
}

log_info "报表模块加载完成"
