# config/pipelines/mcpacket.conf

MCPACKET_INPUT_FILE="${MCPACKET_INPUT_FILE:-$PROJECT_ROOT/modules/mcpacket/data/list}"
MCPACKET_DEVICE_OUTPUT_FILE="${MCPACKET_DEVICE_OUTPUT_FILE:-$RESULT_BASE_DIR/mcpacket/summary_${MCPACKET_TARGET_DATE}.csv}"
MCPACKET_TOTAL_OUTPUT_FILE="${MCPACKET_TOTAL_OUTPUT_FILE:-$RESULT_BASE_DIR/mcpacket/all_summary_${MCPACKET_TARGET_DATE}.csv}"

export MCPACKET_INPUT_FILE MCPACKET_DEVICE_OUTPUT_FILE MCPACKET_TOTAL_OUTPUT_FILE
