# config/nostream.conf 

NOSTREAM_REMOTE_RUNLOG_DIR="${NOSTREAM_REMOTE_RUNLOG_DIR:-/home/logs}"
NOSTREAM_FILTER_KEY1="${NOSTREAM_FILTER_KEY1:-no for.*no}"
NOSTREAM_MAX_PARALLEL="${NOSTREAM_MAX_PARALLEL:-2}"
NOSTREAM_SSH_OPTS="${NOSTREAM_SSH_OPTS:--n -o BatchMode=yes -o ConnectTimeout=10 -q}"

export NOSTREAM_REMOTE_RUNLOG_DIR NOSTREAM_FILTER_KEY1 NOSTREAM_MAX_PARALLEL NOSTREAM_SSH_OPTS
